version: 1.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform: Any CPU
configuration: Release
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
before_build:
  - nuget restore
build:
  verbosity: minimal
test:
  assemblies: Src/Couchbase.Linq.UnitTests.Couchbase.Linq.UnitTests.csproj
