version: 1.0.{build}
platform: Any CPU
configuration: Release
before_build:
  - nuget restore
build:
  verbosity: minimal
test:
  assemblies: Src/Couchbase.Linq.UnitTests.Couchbase.Linq.UnitTests.csproj
